# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'itunesmusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'SwiftyJSON'

  # Pods for itunesmusic

  target 'itunesmusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'itunesmusicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
